# Generated by Django 4.0.6 on 2022-07-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
