# Generated by Django 4.0.6 on 2022-07-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_coinlist_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinlist',
            name='coinname',
            field=models.CharField(choices=[('BTC', 'BTCUSDT'), ('ETH', 'ETHUSDT'), ('BNB', 'BNBUSDT'), ('ADA', 'ADAUSDT'), ('LTC', 'LTCUSDT')], default='BTC', max_length=3),
        ),
    ]
