# Generated by Django 4.0.6 on 2022-07-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_coinlist_coinname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='upload_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
